name: Docker Image CI

on:
  push:
    branches: [ foxy ]
  pull_request:
    branches: [ foxy ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --pull --rm -f ./Dockerfile  -t gdwyer/ros:$GITHUB_REF .
